### ISSUE TITLE
Display furigana to words in kanji

### ISSUE THREAD

**Issue by Kohoshi12** [johnfactotum/quick-lookup#13]
The wikitionary source commonly show the furigana of the kanji, but the program does not show it.

**Comment by johnfactotum** [comment]
This is a limitation of the current Wiktionary API.

For example, if you go to https://en.wiktionary.org/api/rest_v1/page/definition/%E8%84%82%E9%B0%AD, you'd see that the response contains no furigana or romaji even though they are present in the Wiktionary page: https://en.wiktionary.org/wiki/%E8%84%82%E9%B0%AD.

It would certainly be possible to add them if we parse Wiktionary pages ourselves, but I've decided long ago that it seems much simpler and more reliable to use the official API. Plus if bugs like these are fixed for the API, it would benefit everyone, not just users of this application.

**Comment by johnfactotum** [comment]
Also note that, for some reason, the Wiktionary API is currently bugged for queries of single kanji characters, meaning that the API is not currently very usable for the CJK languages. That didn't used to happen when I used to manually parse Wiktionary pages, so it's another thing that I noticed when I began using the REST API. Also, the API does not support pronunciations (in IPA), which is another bummer...
