### ISSUE TITLE
Make able to search for japanese words by romaji writing

### ISSUE THREAD

**Issue by Kohoshi12** [johnfactotum/quick-lookup#14]
Any japanese dictionary program like Sumatora allow the user to search for words using romaji. If you don't know what's romaji, it's just the common alphabet used by many languages. This probably very possible because of kana which many times shows the pronunciation of a japanese kanji.

**Comment by johnfactotum** [comment]
It _is_ possible to look up words with romaji. For example, see this screenshot:

![image](https://user-images.githubusercontent.com/50942278/101231959-9eb40100-36a6-11eb-9b5b-b2ebcbd1b433.png)

But it obviously depends on Wiktionary's data, so you need to lookup, for example, "aizō" for "あいぞう", instead of "aizo" or "aizou", because that's how Wiktionary is at the moment.

**Comment by Kohoshi12** [comment]
On Wikitionary the search for words in romaji is better to search to specific words than the program. Some words are just not easy to search using romaji on the program, because there's no search suggestion on the program. 

![Captura de tela de 2020-12-07 19-57-09](https://user-images.githubusercontent.com/74657968/101342959-a18d3c80-38c6-11eb-8b9a-342e543487d7.png)

![Captura de tela de 2020-12-07 19-58-10](https://user-images.githubusercontent.com/74657968/101343166-ee711300-38c6-11eb-9043-deb1332d57d5.png)

**Comment by Kohoshi12** [comment]
If you search for a word like _nihongo_, the result is the same word in kana, にほんご, but the text of the word does not lead to the kanji word, 日本語, on the program. But the same search on Wikitionary leads from the kana word to the kanji word and then the meaning of the word, not just the writing in kana and kanji.

**Comment by johnfactotum** [comment]
> Some words are just not easy to search using romaji on the program, because there's no search suggestion on the program.

See #7.

> If you search for a word like _nihongo_, the result is the same word in kana, にほんご, but the text of the word does not lead to the kanji word, 日本語, on the program.

In this particular example, the Wiktionary API doesn't provide a definition for "にほんご": https://en.wiktionary.org/api/rest_v1/page/definition/にほんご. And this seems to be due to the API not supporting the [`{{ja-see}}` template](https://en.wiktionary.org/wiki/Template:ja-see).
