### ISSUE TITLE
Make search more coarse-grained?

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/quick-lookup#2]
Is it possible to make the search more coarse-grained? Typing "ttip", for example, doesn't yield a result, whereas "TTIP" does. This could also be extended to include hits when words are misspelled.

**Comment by johnfactotum** [comment]
This is not supported by Wiktionary's API.

It already tries to look up the lower case version of a string when the original string cannot be found. Anything more complicated than that is too much work to implement.

**Comment by digitalethics** [comment]
> This is not supported by Wiktionary's API.

I see.
