### ISSUE TITLE
ComboBox is broken on GTK 4

### ISSUE THREAD

**Issue by johnfactotum** [johnfactotum/quick-lookup#28]
It's a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/3674

**Comment by kdwk** [comment]
https://user-images.githubusercontent.com/39268094/153176190-87117018-6a9a-4bb0-bc93-6160a8188c3f.mp4

Hi, Dialect seems to be using a scrollable widget for language selection. Would that be applicable here?

**Comment by johnfactotum** [comment]
Dialect uses a custom popover, with a list view. We could do something similar but that would essentially be re-implementing Gtk.ComboBox, which I'd rather not do.

There's the new Gtk.DropDown widget (which is supposed to supersede the combobox), the behavior of which is actually the same as the custom widget used in Dialect. Unfortunately we need text entry support, which Gtk.DropDown doesn't have.

**Comment by johnfactotum** [comment]
This has been fixed in GTK.
