### ISSUE TITLE
Backporting to Foliate? 

### ISSUE THREAD

**Issue by digitalethics** [johnfactotum/quick-lookup#3]
When improvements are implemented in quick-lookup would these be backported (not sure what term to use in this case) to Foliate as the latter also includes Wiktionary? Obviously this is a standalone programme but I am just wondering whether the component used in Foliate is the same or relies upon a different implementation of Wiktionary.

**Comment by johnfactotum** [comment]
It's already ported to Foliate 2.0.0.
