### ISSUE TITLE
System wide look up

### ISSUE THREAD

**Issue by retesta** [johnfactotum/quick-lookup#6]
I would love if there was the ability to right click (and/or press a keyboard shortcut) on a selected word anywhere on the OS and have an option to see its definition in the Quick LookUp app. Similar to how you can get definitions on Mac OS by right clicking > define or 3 finger tapping on a word.

I feel this would make the quick in Quick LookUp even quicker... (ba-dum-tss)

**Comment by johnfactotum** [comment]
I've added a `--selection` option. When launched in this mode, it will look up the selected text (primary selection) when the window is focused.

So now you can set a shortcut for `quick-lookup --selection`, and it will launch the app and look up the selected text.

In GNOME, a global shortcut can be set in the _Keyboard Shortcuts_ section in _Settings_:

![image](https://user-images.githubusercontent.com/50942278/85206175-b7567780-b30f-11ea-804d-3692c9a12e14.png)

**Comment by retesta** [comment]
Amazing man. Much appreciated!

Also, if you have installed Quick Lookup from Flathub, the command used should be: `flatpak run com.github.johnfactotum.QuickLookup --selection`

**Comment by thagorastos** [comment]
> Amazing man. Much appreciated!
> 
> Also, if you have installed Quick Lookup from Flathub, the command used should be: `flatpak run com.github.johnfactotum.QuickLookup --selection`

Please add this info to the README.
