### ISSUE TITLE
[Feature Request] Dark mode 

### ISSUE THREAD

**Issue by benjezzy** [johnfactotum/quick-lookup#9]
Currently using the [flatpak](https://flathub.org/apps/details/com.github.johnfactotum.QuickLookup) version but there's no option to toggle a dark mode (which is easier on the eyes). 

Could this be implemented? If not, could it align to the gtk theme that is already set? 

Thanks!

**Comment by johnfactotum** [comment]
It should already use the system GTK theme if the corresponding [theme extension is installed](https://docs.flatpak.org/en/latest/desktop-integration.html#instructions-for-gtk).

I suppose we can add an option to enable app-specific dark mode. But note that if your system GTK theme isn't available in the Flatpak environment, it will fallback to a version of Adwaita that does _not_ have a dark variant and the dark mode setting would have no effect. In other words, you should install the corresponding Flatpak theme no matter what.

**Comment by HarryMichal** [comment]
This is handled automatically by libadwaita.

**Comment by benjezzy** [comment]
Seems like it depends on which version you run.

On the same system: 
- When using the [Flatpak version](https://flathub.org/apps/details/com.github.johnfactotum.QuickLookup) (currently on v1.2) --> theme is white (despite having corresponding dark theme installed via Flatpak) 
Error message: 
`Gtk-Message: 23:23:10.582: Failed to load module "xapp-gtk3-module"`
`Gtk-Message: 23:23:10.582: Failed to load module "canberra-gtk-module"`

- When using the [AUR version](https://aur.archlinux.org/packages/quick-lookup) (currently on v2.0) --> theme is dark 

Looks like I'll be sticking with the AUR version for now, happy for this issue to be closed (assuming it'll be solved whenever the Flatpak version gets v2.0)

**Comment by johnfactotum** [comment]
Right. This is fixed with libadwaita in v2.0. So I guess this can be closed now.

The Flatpak version doesn't have v2.0 because technically, WebKitGTK isn't stable for GTK 4 yet, so it's not in the stable GNOME runtime yet (I think).
